- name: set prompt
  ansible.builtin.shell: set-prompt elk

- name: copy service file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: start elasticsearch
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started

