- name: set prompt
  ansible.builtin.shell: set-prompt elk

- name: copy service file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: start elasticsearch
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: true

- name: install kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: update kibana server port
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.port: 5601'
    line: 'server.port: 5601'

- name: update kibana server host
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.host: "localhost"'
    line: 'server.host: "0.0.0.0"'

- name: start kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: true
