format_version: 10
pipelines:
  Grafana:
    group: Tools
    materials:
      git-da613e5:
        git: https://github.com/s-devops-i3/tools-automation.git
        shallow_clone: false
        auto_update: true
        branch: main
    #    secure_variables:
    #      TF_VAR_vault_token: AES:Q67ao+nSos1av1ldpBh3nw==:FOP/PO/1Jxq3QtP+a2x3r3Biq1/WDjvIHSBY3g2Yplw=
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            apply:
              tasks:
                - exec: {command: ansible-playbook, arguments: [ "-i", "grafana-internal.shujadevops.shop,", "-e", "tool_name=grafana", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" , "tools.yml" ], run_if: passed}