format_version: 10
pipelines:
  Prometheus:
    group: Tools
    materials:
      git-da613e5:
        git: https://github.com/s-devops-i3/tools-automation.git
        shallow_clone: false
        auto_update: true
        branch: main
        secure_variables:
          TF_VAR_vault_token: AES:tMa6doi5yndKRc+n2T/SiQ==:XGTDT/yZ25RZ3ORgbR1ktGSIRualXzy2eRg66E19T4U=
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            apply:
              tasks:
                - exec: {command: ansible-playbook, arguments: [ "-i", "prometheus-internal.shujadevops.shop,", "-e", "tool_name=prometheus", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" , "tools.yml" ], run_if: passed}