- name: set up yum repo
  ansible.builtin.shell: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: start vault
  ansible.builtin.systemd_service:
    name: vault
    state: started
    enabled: true

